// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SellerLite.Infrastructure.Persistence;

#nullable disable

namespace SellerLite.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421095920_SeedDataFinal")]
    partial class SeedDataFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SellerLite.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00002711-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Thời trang 1",
                            CustomerPhone = "0901000001",
                            OrderNumber = "ORD-F-0001",
                            ShippingFee = 30000m,
                            Status = 1,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000"),
                            TotalPrice = 280000m
                        },
                        new
                        {
                            Id = new Guid("00002712-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Thời trang 2",
                            CustomerPhone = "0901000002",
                            OrderNumber = "ORD-F-0002",
                            ShippingFee = 30000m,
                            Status = 2,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000"),
                            TotalPrice = 420000m
                        },
                        new
                        {
                            Id = new Guid("00002713-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Thời trang 3",
                            CustomerPhone = "0901000003",
                            OrderNumber = "ORD-F-0003",
                            ShippingFee = 30000m,
                            Status = 3,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000"),
                            TotalPrice = 165000m
                        },
                        new
                        {
                            Id = new Guid("00002714-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Thời trang 4",
                            CustomerPhone = "0901000004",
                            OrderNumber = "ORD-F-0004",
                            ShippingFee = 30000m,
                            Status = 4,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000"),
                            TotalPrice = 310000m
                        },
                        new
                        {
                            Id = new Guid("00002715-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Thời trang 5",
                            CustomerPhone = "0901000005",
                            OrderNumber = "ORD-F-0005",
                            ShippingFee = 30000m,
                            Status = 0,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000"),
                            TotalPrice = 465000m
                        },
                        new
                        {
                            Id = new Guid("00002716-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Thời trang 6",
                            CustomerPhone = "0901000006",
                            OrderNumber = "ORD-F-0006",
                            ShippingFee = 30000m,
                            Status = 1,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000"),
                            TotalPrice = 180000m
                        },
                        new
                        {
                            Id = new Guid("00002717-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Thời trang 7",
                            CustomerPhone = "0901000007",
                            OrderNumber = "ORD-F-0007",
                            ShippingFee = 30000m,
                            Status = 2,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000"),
                            TotalPrice = 340000m
                        },
                        new
                        {
                            Id = new Guid("00002718-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Thời trang 8",
                            CustomerPhone = "0901000008",
                            OrderNumber = "ORD-F-0008",
                            ShippingFee = 30000m,
                            Status = 3,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000"),
                            TotalPrice = 510000m
                        },
                        new
                        {
                            Id = new Guid("00002719-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Thời trang 9",
                            CustomerPhone = "0901000009",
                            OrderNumber = "ORD-F-0009",
                            ShippingFee = 30000m,
                            Status = 4,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000"),
                            TotalPrice = 195000m
                        },
                        new
                        {
                            Id = new Guid("0000271a-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Thời trang 10",
                            CustomerPhone = "09010000010",
                            OrderNumber = "ORD-F-0010",
                            ShippingFee = 30000m,
                            Status = 0,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000"),
                            TotalPrice = 370000m
                        },
                        new
                        {
                            Id = new Guid("00004e21-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Công nghệ 1",
                            CustomerPhone = "0912000001",
                            OrderNumber = "ORD-T-0001",
                            ShippingFee = 20000m,
                            Status = 1,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000"),
                            TotalPrice = 196000m
                        },
                        new
                        {
                            Id = new Guid("00004e22-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Công nghệ 2",
                            CustomerPhone = "0912000002",
                            OrderNumber = "ORD-T-0002",
                            ShippingFee = 20000m,
                            Status = 2,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000"),
                            TotalPrice = 111000m
                        },
                        new
                        {
                            Id = new Guid("00004e23-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Công nghệ 3",
                            CustomerPhone = "0912000003",
                            OrderNumber = "ORD-T-0003",
                            ShippingFee = 20000m,
                            Status = 3,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000"),
                            TotalPrice = 208000m
                        },
                        new
                        {
                            Id = new Guid("00004e24-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Công nghệ 4",
                            CustomerPhone = "0912000004",
                            OrderNumber = "ORD-T-0004",
                            ShippingFee = 20000m,
                            Status = 4,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000"),
                            TotalPrice = 117000m
                        },
                        new
                        {
                            Id = new Guid("00004e25-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Công nghệ 5",
                            CustomerPhone = "0912000005",
                            OrderNumber = "ORD-T-0005",
                            ShippingFee = 20000m,
                            Status = 0,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000"),
                            TotalPrice = 220000m
                        },
                        new
                        {
                            Id = new Guid("00004e26-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Công nghệ 6",
                            CustomerPhone = "0912000006",
                            OrderNumber = "ORD-T-0006",
                            ShippingFee = 20000m,
                            Status = 1,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000"),
                            TotalPrice = 123000m
                        },
                        new
                        {
                            Id = new Guid("00004e27-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Công nghệ 7",
                            CustomerPhone = "0912000007",
                            OrderNumber = "ORD-T-0007",
                            ShippingFee = 20000m,
                            Status = 2,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000"),
                            TotalPrice = 232000m
                        },
                        new
                        {
                            Id = new Guid("00004e28-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Công nghệ 8",
                            CustomerPhone = "0912000008",
                            OrderNumber = "ORD-T-0008",
                            ShippingFee = 20000m,
                            Status = 3,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000"),
                            TotalPrice = 129000m
                        },
                        new
                        {
                            Id = new Guid("00004e29-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Công nghệ 9",
                            CustomerPhone = "0912000009",
                            OrderNumber = "ORD-T-0009",
                            ShippingFee = 20000m,
                            Status = 4,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000"),
                            TotalPrice = 244000m
                        },
                        new
                        {
                            Id = new Guid("00004e2a-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Khách hàng Công nghệ 10",
                            CustomerPhone = "09120000010",
                            OrderNumber = "ORD-T-0010",
                            ShippingFee = 20000m,
                            Status = 0,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000"),
                            TotalPrice = 135000m
                        });
                });

            modelBuilder.Entity("SellerLite.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00002af9-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00002711-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000003e9-0000-0000-0000-000000000000"),
                            Quantity = 2,
                            UnitPrice = 125000m
                        },
                        new
                        {
                            Id = new Guid("00002afa-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00002712-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000003ea-0000-0000-0000-000000000000"),
                            Quantity = 3,
                            UnitPrice = 130000m
                        },
                        new
                        {
                            Id = new Guid("00002afb-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00002713-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000003eb-0000-0000-0000-000000000000"),
                            Quantity = 1,
                            UnitPrice = 135000m
                        },
                        new
                        {
                            Id = new Guid("00002afc-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00002714-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000003ec-0000-0000-0000-000000000000"),
                            Quantity = 2,
                            UnitPrice = 140000m
                        },
                        new
                        {
                            Id = new Guid("00002afd-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00002715-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000003ed-0000-0000-0000-000000000000"),
                            Quantity = 3,
                            UnitPrice = 145000m
                        },
                        new
                        {
                            Id = new Guid("00002afe-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00002716-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000003ee-0000-0000-0000-000000000000"),
                            Quantity = 1,
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = new Guid("00002aff-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00002717-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000003ef-0000-0000-0000-000000000000"),
                            Quantity = 2,
                            UnitPrice = 155000m
                        },
                        new
                        {
                            Id = new Guid("00002b00-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00002718-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000003f0-0000-0000-0000-000000000000"),
                            Quantity = 3,
                            UnitPrice = 160000m
                        },
                        new
                        {
                            Id = new Guid("00002b01-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00002719-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000003f1-0000-0000-0000-000000000000"),
                            Quantity = 1,
                            UnitPrice = 165000m
                        },
                        new
                        {
                            Id = new Guid("00002b02-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("0000271a-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000003f2-0000-0000-0000-000000000000"),
                            Quantity = 2,
                            UnitPrice = 170000m
                        },
                        new
                        {
                            Id = new Guid("00005209-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00004e21-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000007d1-0000-0000-0000-000000000000"),
                            Quantity = 2,
                            UnitPrice = 88000m
                        },
                        new
                        {
                            Id = new Guid("0000520a-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00004e22-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000007d2-0000-0000-0000-000000000000"),
                            Quantity = 1,
                            UnitPrice = 91000m
                        },
                        new
                        {
                            Id = new Guid("0000520b-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00004e23-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000007d3-0000-0000-0000-000000000000"),
                            Quantity = 2,
                            UnitPrice = 94000m
                        },
                        new
                        {
                            Id = new Guid("0000520c-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00004e24-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000007d4-0000-0000-0000-000000000000"),
                            Quantity = 1,
                            UnitPrice = 97000m
                        },
                        new
                        {
                            Id = new Guid("0000520d-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00004e25-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000007d5-0000-0000-0000-000000000000"),
                            Quantity = 2,
                            UnitPrice = 100000m
                        },
                        new
                        {
                            Id = new Guid("0000520e-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00004e26-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000007d6-0000-0000-0000-000000000000"),
                            Quantity = 1,
                            UnitPrice = 103000m
                        },
                        new
                        {
                            Id = new Guid("0000520f-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00004e27-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000007d7-0000-0000-0000-000000000000"),
                            Quantity = 2,
                            UnitPrice = 106000m
                        },
                        new
                        {
                            Id = new Guid("00005210-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00004e28-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000007d8-0000-0000-0000-000000000000"),
                            Quantity = 1,
                            UnitPrice = 109000m
                        },
                        new
                        {
                            Id = new Guid("00005211-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00004e29-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000007d9-0000-0000-0000-000000000000"),
                            Quantity = 2,
                            UnitPrice = 112000m
                        },
                        new
                        {
                            Id = new Guid("00005212-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 4, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("00004e2a-0000-0000-0000-000000000000"),
                            ProductId = new Guid("000007da-0000-0000-0000-000000000000"),
                            Quantity = 1,
                            UnitPrice = 115000m
                        });
                });

            modelBuilder.Entity("SellerLite.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("000003e9-0000-0000-0000-000000000000"),
                            CostPrice = 52000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 5,
                            Name = "Áo thun Polo Nam 1",
                            SKU = "FASH-001",
                            SalePrice = 125000m,
                            Stock = 51,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000003ea-0000-0000-0000-000000000000"),
                            CostPrice = 54000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 5,
                            Name = "Áo thun Polo Nam 2",
                            SKU = "FASH-002",
                            SalePrice = 130000m,
                            Stock = 52,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000003eb-0000-0000-0000-000000000000"),
                            CostPrice = 56000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 5,
                            Name = "Áo thun Polo Nam 3",
                            SKU = "FASH-003",
                            SalePrice = 135000m,
                            Stock = 53,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000003ec-0000-0000-0000-000000000000"),
                            CostPrice = 58000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 5,
                            Name = "Áo thun Polo Nam 4",
                            SKU = "FASH-004",
                            SalePrice = 140000m,
                            Stock = 54,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000003ed-0000-0000-0000-000000000000"),
                            CostPrice = 60000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 5,
                            Name = "Áo thun Polo Nam 5",
                            SKU = "FASH-005",
                            SalePrice = 145000m,
                            Stock = 55,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000003ee-0000-0000-0000-000000000000"),
                            CostPrice = 62000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 5,
                            Name = "Áo thun Polo Nam 6",
                            SKU = "FASH-006",
                            SalePrice = 150000m,
                            Stock = 56,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000003ef-0000-0000-0000-000000000000"),
                            CostPrice = 64000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 5,
                            Name = "Áo thun Polo Nam 7",
                            SKU = "FASH-007",
                            SalePrice = 155000m,
                            Stock = 57,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000003f0-0000-0000-0000-000000000000"),
                            CostPrice = 66000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 5,
                            Name = "Áo thun Polo Nam 8",
                            SKU = "FASH-008",
                            SalePrice = 160000m,
                            Stock = 58,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000003f1-0000-0000-0000-000000000000"),
                            CostPrice = 68000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 5,
                            Name = "Áo thun Polo Nam 9",
                            SKU = "FASH-009",
                            SalePrice = 165000m,
                            Stock = 59,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000003f2-0000-0000-0000-000000000000"),
                            CostPrice = 70000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 5,
                            Name = "Áo thun Polo Nam 10",
                            SKU = "FASH-010",
                            SalePrice = 170000m,
                            Stock = 60,
                            TenantId = new Guid("00000064-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000007d1-0000-0000-0000-000000000000"),
                            CostPrice = 31000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 10,
                            Name = "Cáp sạc USB-C 1",
                            SKU = "TECH-001",
                            SalePrice = 88000m,
                            Stock = 101,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000007d2-0000-0000-0000-000000000000"),
                            CostPrice = 32000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 10,
                            Name = "Cáp sạc USB-C 2",
                            SKU = "TECH-002",
                            SalePrice = 91000m,
                            Stock = 102,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000007d3-0000-0000-0000-000000000000"),
                            CostPrice = 33000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 10,
                            Name = "Cáp sạc USB-C 3",
                            SKU = "TECH-003",
                            SalePrice = 94000m,
                            Stock = 103,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000007d4-0000-0000-0000-000000000000"),
                            CostPrice = 34000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 10,
                            Name = "Cáp sạc USB-C 4",
                            SKU = "TECH-004",
                            SalePrice = 97000m,
                            Stock = 104,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000007d5-0000-0000-0000-000000000000"),
                            CostPrice = 35000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 10,
                            Name = "Cáp sạc USB-C 5",
                            SKU = "TECH-005",
                            SalePrice = 100000m,
                            Stock = 105,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000007d6-0000-0000-0000-000000000000"),
                            CostPrice = 36000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 10,
                            Name = "Cáp sạc USB-C 6",
                            SKU = "TECH-006",
                            SalePrice = 103000m,
                            Stock = 106,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000007d7-0000-0000-0000-000000000000"),
                            CostPrice = 37000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 10,
                            Name = "Cáp sạc USB-C 7",
                            SKU = "TECH-007",
                            SalePrice = 106000m,
                            Stock = 107,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000007d8-0000-0000-0000-000000000000"),
                            CostPrice = 38000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 10,
                            Name = "Cáp sạc USB-C 8",
                            SKU = "TECH-008",
                            SalePrice = 109000m,
                            Stock = 108,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000007d9-0000-0000-0000-000000000000"),
                            CostPrice = 39000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 10,
                            Name = "Cáp sạc USB-C 9",
                            SKU = "TECH-009",
                            SalePrice = 112000m,
                            Stock = 109,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("000007da-0000-0000-0000-000000000000"),
                            CostPrice = 40000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LowStockThreshold = 10,
                            Name = "Cáp sạc USB-C 10",
                            SKU = "TECH-010",
                            SalePrice = 115000m,
                            Stock = 110,
                            TenantId = new Guid("000000c8-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("SellerLite.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000064-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chuyên quần áo nam nữ",
                            Name = "Shop Thời Trang"
                        },
                        new
                        {
                            Id = new Guid("000000c8-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phụ kiện điện thoại và máy tính",
                            Name = "Cửa Hàng Phụ Kiện"
                        });
                });

            modelBuilder.Entity("SellerLite.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("SellerLite.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SellerLite.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
